### PR TITLE
Remove duplicates from HTML index table + Overloaded methods

### PR DESCRIPTION
**Pull request by ArtjomsBrovkins**
When creating documentation in HTML format, multiple links are generated in index table, if both - package specification and body are selected as parsed objects.

### CODE REVIEW

**Comment by vincentmorneau** [comment]
Great fix. I had seen the issue too. Thanks @intrx

**Comment by ArtjomsBrovkins** [comment]
Thanks!

**Comment by ArtjomsBrovkins** [comment]
Added one more change, this time to overloaded methods. Copied a function, which accepts a method name as a parameter and adds it to local list (created for each file). If such method exists in a list, postfix in format "-n" is appended to method name.

**Comment by ArtjomsBrovkins** [comment]
Solution used for overloaded method function
http://stackoverflow.com/questions/10643933/renaming-duplicates-in-javascript-array

**Pull request merged**
